# .streamlit/secrets.toml  ← one single block, everything inside it
[connections.gsheets]
type = "service_account"

# ➊  put the URL **inside** this block
spreadsheet = "https://docs.google.com/spreadsheets/d/1HiQfv8J8NkWo11itq1C49KGz2BF7JJUxoQTvisHar70"
[connections.gsheets.service_account_info]
project_id = "eternal-ruler-460403-n8"
private_key_id = "5d8c456e0e719ef6d153b784bfeb4f5f07b37aba"

# ➋  make sure the key is triple-quoted, exactly as below
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCU7DwZ3TnLRmUg\nSQb9CaM1kZKZKGbcZkWPfp9MEjkCpsGDFwLowqzksuKMYq9P8zYc+Xr5QteJ5aFP\ncDx06Tot4KBXAw7l+mR5NebP8bOrI0J/1pTdy1++tHLWaAKNiBTfxRoOVycN0lkh\nBPp7qiG5guk6klIo29SIrru4pOR2L70q3vXpvHCiwOFMDmAcH9XQ/qsCckPSQKAs\nzGnxhQyk95SOYSK0VqQ8A8lTjT0anNhiYCxSfAZpFdspriLw3UpGadXO2z6DNEBH\ngcp3PjSZOBqVbBte0wvlyzpNFXmSqL8LjJCZ2yjgRz1Uyr59XxJNDmyeMSrzNmZ9\nwVPHXl+LAgMBAAECggEAFyhRBDiZdxmgOhABDTIFdhwH7tcQf69Lm8+1169xvA7Q\nQqE+a5FyLzH99pSV7FnGjWTiEYaqW6AgoGi0jf2CdYXbiQxJscto+kw+cxGDvdYC\nzjxA8+hfIBmRTfPoibeif1V4AsjcotKV14Odq8M98UoBGIGOUxo0B3kcac8CU7pF\n3c25jzrCm40w0YJVmQ+ZfEcF2z8V5CMrRVdnNC9hgynBa+SpEaa1IhLJQEEWZuH4\nnCNrsdngUfpAXcPOcEqJUVbBiWAf8wEkwuJUttEL8gwNwGq+AphZKVZV+NLTtB4D\no0VPlxTWPV1BS3LWx/rwkuaZW1znnUQZNgteGRV+eQKBgQDO1hKPlLdSV+AKMeQY\njiPsvzNS4vREPK8niKUwP/mMk7VPBfyXc6vo0CWTz7qxpPCTCW/m7J40t2T8K6Ah\ngxMI4gGh+x89snpelvx4eZGTbcSazjOsovnMmzDuiStWt32oq2YxN3ClpfYOgldd\nvWLv/26kmPL5amPn4YIf6ACZNwKBgQC4UiVdytnQsDffWWONBvU9ZrAV39BdM5+A\n0U1rZEKvNFHoJQpQKXyRDJBg5YGkJ1BLH0/h/Y2UtLdRfWjpFb6PKuFChOP8hDuV\nRe71+M6ZGpIGdf6R6zDyrsUEhTg4vLrOZieoP5BJC1rjSwY5kSSJ2kr+gdUkMPvu\nUPjjOa8GTQKBgHFbpgSHDwnUG3e67DYBAPNpvuk4dYNIdv6Fx3LwPQaslXvf3hXr\nUVZhbZbbDIj7ytXrICdBm1ts/62tAzAatD30D80E4pRf0u0wduJYTk6spEnrpSqC\nj8FxdJnnF5eJLRdaCMIEjnpawMYm7Vb0ytqZ9bvED7Zedq7JSxXNgzZ1AoGADa97\nusUO+yG6ZEj8zUHQ/6gaNuWRUPo+Q5BG0Ux2bw/RbQ0jAOSzrQljxu4DfC63FXzT\nr5Hl6z6nxdMr8PJ+XZ7vbsLzMpKW4fR5U6YPoOqKIRStvCPcVIiJdFZ34C6TKDQJ\nicJ+cg33x5yQb8HJFrswikkVjERe0EkO0cA8sJkCgYBTl9EFzMrmwfIJDKa/2E5P\nwsrL0Z6WcLM2rnRlcQev3Cx3S/P7AoMMqAmeatJoq6QJvlApmAACccaEz+7H/byT\njOBW4RFC4BjCNxOY1mJgpjGSetzGEel6gZ+mAGJLpTGTl+aLfgFwG4eM7zuSSH0C\nIxLjcwOZZs3W0fXCGzHTXg==
-----END PRIVATE KEY-----"""

client_email = "aditya-shahane-971@eternal-ruler-460403-n8.iam.gserviceaccount.com"
client_id    = "106754251296363949623"

auth_uri      = "https://accounts.google.com/o/oauth2/auth"
token_uri     = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url        = "https://www.googleapis.com/robot/v1/metadata/x509/aditya-shahane-971%40eternal-ruler-460403-n8.iam.gserviceaccount.com"
